# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
platform :ios, '7.0'

target "rottentomatoes" do
pod "AFNetworking", "~> 2.0"
pod 'ALAlertBanner', '~>0.3.1'
pod 'MBProgressHUD', '~> 0.8'
end

target "rottentomatoesTests" do

end

