# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "twitter" do
platform:ios,"7.0"
pod 'BDBOAuth1Manager', '~> 1.3'
pod 'AFNetworking'
pod 'AFNetworkActivityLogger', '~> 2.0'
pod 'JSONKit', '~> 1.5pre'

end

target "twitterTests" do

end

